services:
  esphome_server:
    image: ${DOCKER_REGISTRY-}esphomeserver
    build:
      context: .
      dockerfile: ESPHome/ESPHome_Server/Dockerfile
  ihc_controller:
    image: ${DOCKER_REGISTRY-}ihccontrollerservice
    build:
      context: .
      dockerfile: IHC_Controller/IHC_Controller_Service/Dockerfile
